version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./:/app  # Only for development (hot-reload)
      - /app/node_modules  # Isolate node_modules
    environment:
      - NODE_ENV=production